### ISSUE TITLE
`disableOverworldPhantoms` config did not actually prevent phantoms from spawning in overworld

### ISSUE THREAD

**Issue by oOBoomberOo** [Thelnfamous1/Deadly-End-Phantoms#2]
I've enabled the `disableOverworldPhantoms` config but the phantoms still keep spawning in the overworld.

This is the actual config file that I've used in my server.
```toml
#End Phantom Configuration
[end_phantom_configuration]
	#Disable vanilla Phantom spawns in the Overworld [true / false]
	disableOverworldPhantoms = true
	#Allow Phantoms to spawn in End Highlands and End Midlands [true / false]
	enableEndPhantoms = true
	#Minimum group size of Phantoms spawning in the End [0-100, default: 4]
	#Range: 0 ~ 100
	endPhantomMinGroupSize = 4
	#Spawn weight of Phantoms spawning in the End [0-100, default: 5]
	#Range: 0 ~ 100
	endPhantomSpawnWeight = 3
	#Maximum group size of Phantoms spawning in the End [0-100, default: 4]
	#Range: 0 ~ 100
	endPhantomMaxGroupSize = 4
```
